# Generated by Django 4.1 on 2022-09-20 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_products',
            name='product_mrp',
            field=models.IntegerField(blank=True, db_column='product_mrp', null=True),
        ),
    ]
