# Generated by Django 4.1 on 2022-09-20 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_app', '0002_alter_all_products_product_mrp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_products',
            name='product_category',
            field=models.CharField(blank=True, db_column='product_category', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='all_products',
            name='product_description',
            field=models.CharField(blank=True, db_column='product_description', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='all_products',
            name='product_gender',
            field=models.CharField(blank=True, db_column='product_gender', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='all_products',
            name='product_image',
            field=models.ImageField(blank=True, db_column='product_image', null=True, upload_to='product_images/'),
        ),
        migrations.AlterField(
            model_name='all_products',
            name='product_is_trusted',
            field=models.CharField(blank=True, db_column='product_is_trusted', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='all_products',
            name='product_name',
            field=models.CharField(blank=True, db_column='Product_Name', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='all_products',
            name='product_price',
            field=models.IntegerField(blank=True, db_column='product_price', null=True),
        ),
        migrations.AlterField(
            model_name='all_products',
            name='product_rating',
            field=models.CharField(blank=True, db_column='product_rating', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='all_products',
            name='product_review_id',
            field=models.IntegerField(blank=True, db_column='product_review_id', null=True),
        ),
        migrations.AlterField(
            model_name='all_products',
            name='product_specification_1',
            field=models.CharField(blank=True, db_column='product_specification_1', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='all_products',
            name='product_specification_2',
            field=models.CharField(blank=True, db_column='product_specification_2', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='all_products',
            name='product_stock_available',
            field=models.IntegerField(blank=True, db_column='product_stock_available', null=True),
        ),
        migrations.AlterField(
            model_name='all_products',
            name='product_sub_category',
            field=models.CharField(blank=True, db_column='product_sub_category', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='all_products',
            name='product_total_sold',
            field=models.IntegerField(blank=True, db_column='product_total_sold', null=True),
        ),
    ]
