# Generated by Django 4.1 on 2022-09-20 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_app', '0003_alter_all_products_product_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_info',
            name='company_logo',
            field=models.ImageField(db_column='company_logo', upload_to='company_logo/'),
        ),
    ]
